name: Formatter

run-name: Running formatter

on:
  pull_request:
    branches:
      - main
      - staging
      - release**
    paths-ignore:
      - 'vendor/**'
    types:
      - reopened
      - opened
      - synchronize

permissions:
  # Required: allow read access to the content for analysis.
  contents: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: write
  
jobs:
  run-formatter:
    uses: azerlinda/githubworkflows/.github/workflows/formatter.yml@main
    with:
      runs-on: "['ubuntu-latest']"
